### ISSUE TITLE
Suggestion about removing the modal and implement the new folder UX

### ISSUE THREAD

**Issue by Bartmax** [madskristensen/AddAnyFile#7]
I very much like the way the `new folder` UX works. Instead of a modal, it creates a temporary to be named file on filesystem (empty).

If it's possible, may I suggest that design change? 

If you need extra options for some files (like a controller with views, etc) to actually be on a modal, I can suggest to bring that up after the file name is chosen, and only if necessary.

**Comment by madskristensen** [comment]
I looked into that and found that it is problematic from a user experience point of view. Creating a file and make the name editable in Solution Explorer is easy. The problem is that we can't open the file before the user has named the file and given it its final extension. Some of the editors in VS can't handle file extension renames correctly when the file is open. 

Also, if Solution Explorer isn't in focus and you've done Shift+F2 inside the editor window, the extension will create a file in the same folder as the active document. Involving an editable filename in Solution Explorer at this point would not be a good user experience.

**Comment by Bartmax** [comment]
I see and understand. Maybe the visual studio team can work around those issues in the future. Pretty sure they have a huge workload of stuff right now. I can live with the modal :)
